/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sonarData.proto */

#ifndef PROTOBUF_C_sonarData_2eproto__INCLUDED
#define PROTOBUF_C_sonarData_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _SonarData__UngeorefAndTelemetry SonarData__UngeorefAndTelemetry;
typedef struct _SonarData__SonarData SonarData__SonarData;
typedef struct _SonarData__TelemetryDataPosition SonarData__TelemetryDataPosition;
typedef struct _SonarData__TelemetryDataPose SonarData__TelemetryDataPose;
typedef struct _SonarData__TelemetryDataHeading SonarData__TelemetryDataHeading;
typedef struct _SonarData__TelemetryDataDepth SonarData__TelemetryDataDepth;
typedef struct _SonarData__TelemetryDataAltitude SonarData__TelemetryDataAltitude;
typedef struct _SonarData__TestDataRawPoses SonarData__TestDataRawPoses;
typedef struct _SonarData__RawRollAndpitch SonarData__RawRollAndpitch;
typedef struct _SonarData__RawHeading SonarData__RawHeading;


/* --- enums --- */


/* --- messages --- */

/*
 * --------------------- Ungeoreferenced point cloud and telemetry data ---------------------
 */
struct  _SonarData__UngeorefAndTelemetry
{
  ProtobufCMessage base;
  SonarData__SonarData *sonar;
  SonarData__TelemetryDataPosition *position;
  SonarData__TelemetryDataPose *pose;
  SonarData__TelemetryDataHeading *heading;
  SonarData__TelemetryDataDepth *depth;
  SonarData__TelemetryDataAltitude *altitude;
};
#define SONAR_DATA__UNGEOREF__AND__TELEMETRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sonar_data__ungeoref__and__telemetry__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, NULL }


struct  _SonarData__SonarData
{
  ProtobufCMessage base;
  size_t n_pointx;
  float *pointx;
  size_t n_pointy;
  float *pointy;
  size_t n_beamidx;
  int32_t *beamidx;
  size_t n_quality;
  uint32_t *quality;
  size_t n_intensity;
  float *intensity;
};
#define SONAR_DATA__SONAR_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sonar_data__sonar_data__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL }


struct  _SonarData__TelemetryDataPosition
{
  ProtobufCMessage base;
  float latitude;
  float longitude;
  int32_t position_timestep;
};
#define SONAR_DATA__TELEMETRY_DATA_POSITION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sonar_data__telemetry_data_position__descriptor) \
    , 0, 0, 0 }


struct  _SonarData__TelemetryDataPose
{
  ProtobufCMessage base;
  float roll;
  float pitch;
  int32_t pose_timestep;
};
#define SONAR_DATA__TELEMETRY_DATA_POSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sonar_data__telemetry_data_pose__descriptor) \
    , 0, 0, 0 }


struct  _SonarData__TelemetryDataHeading
{
  ProtobufCMessage base;
  float heading;
  int32_t heading_timestep;
};
#define SONAR_DATA__TELEMETRY_DATA_HEADING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sonar_data__telemetry_data_heading__descriptor) \
    , 0, 0 }


struct  _SonarData__TelemetryDataDepth
{
  ProtobufCMessage base;
  float depth;
  int32_t depth_timestep;
};
#define SONAR_DATA__TELEMETRY_DATA_DEPTH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sonar_data__telemetry_data_depth__descriptor) \
    , 0, 0 }


struct  _SonarData__TelemetryDataAltitude
{
  ProtobufCMessage base;
  float altitude;
  int32_t altitude_timestep;
};
#define SONAR_DATA__TELEMETRY_DATA_ALTITUDE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sonar_data__telemetry_data_altitude__descriptor) \
    , 0, 0 }


/*
 * --------------- Poses before interpolation ("raw poses") for testing --------------------------
 */
struct  _SonarData__TestDataRawPoses
{
  ProtobufCMessage base;
  SonarData__RawRollAndpitch *raw_rollandpitch;
  SonarData__RawHeading *raw_heading;
};
#define SONAR_DATA__TEST_DATA__RAW_POSES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sonar_data__test_data__raw_poses__descriptor) \
    , NULL, NULL }


struct  _SonarData__RawRollAndpitch
{
  ProtobufCMessage base;
  float raw_roll;
  float raw_pitch;
  int32_t raw_pose_timestep;
};
#define SONAR_DATA__RAW_ROLL_ANDPITCH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sonar_data__raw_roll_andpitch__descriptor) \
    , 0, 0, 0 }


struct  _SonarData__RawHeading
{
  ProtobufCMessage base;
  float raw_heading;
  int32_t raw_heading_timestep;
};
#define SONAR_DATA__RAW_HEADING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sonar_data__raw_heading__descriptor) \
    , 0, 0 }


/* SonarData__UngeorefAndTelemetry methods */
void   sonar_data__ungeoref__and__telemetry__init
                     (SonarData__UngeorefAndTelemetry         *message);
size_t sonar_data__ungeoref__and__telemetry__get_packed_size
                     (const SonarData__UngeorefAndTelemetry   *message);
size_t sonar_data__ungeoref__and__telemetry__pack
                     (const SonarData__UngeorefAndTelemetry   *message,
                      uint8_t             *out);
size_t sonar_data__ungeoref__and__telemetry__pack_to_buffer
                     (const SonarData__UngeorefAndTelemetry   *message,
                      ProtobufCBuffer     *buffer);
SonarData__UngeorefAndTelemetry *
       sonar_data__ungeoref__and__telemetry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sonar_data__ungeoref__and__telemetry__free_unpacked
                     (SonarData__UngeorefAndTelemetry *message,
                      ProtobufCAllocator *allocator);
/* SonarData__SonarData methods */
void   sonar_data__sonar_data__init
                     (SonarData__SonarData         *message);
size_t sonar_data__sonar_data__get_packed_size
                     (const SonarData__SonarData   *message);
size_t sonar_data__sonar_data__pack
                     (const SonarData__SonarData   *message,
                      uint8_t             *out);
size_t sonar_data__sonar_data__pack_to_buffer
                     (const SonarData__SonarData   *message,
                      ProtobufCBuffer     *buffer);
SonarData__SonarData *
       sonar_data__sonar_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sonar_data__sonar_data__free_unpacked
                     (SonarData__SonarData *message,
                      ProtobufCAllocator *allocator);
/* SonarData__TelemetryDataPosition methods */
void   sonar_data__telemetry_data_position__init
                     (SonarData__TelemetryDataPosition         *message);
size_t sonar_data__telemetry_data_position__get_packed_size
                     (const SonarData__TelemetryDataPosition   *message);
size_t sonar_data__telemetry_data_position__pack
                     (const SonarData__TelemetryDataPosition   *message,
                      uint8_t             *out);
size_t sonar_data__telemetry_data_position__pack_to_buffer
                     (const SonarData__TelemetryDataPosition   *message,
                      ProtobufCBuffer     *buffer);
SonarData__TelemetryDataPosition *
       sonar_data__telemetry_data_position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sonar_data__telemetry_data_position__free_unpacked
                     (SonarData__TelemetryDataPosition *message,
                      ProtobufCAllocator *allocator);
/* SonarData__TelemetryDataPose methods */
void   sonar_data__telemetry_data_pose__init
                     (SonarData__TelemetryDataPose         *message);
size_t sonar_data__telemetry_data_pose__get_packed_size
                     (const SonarData__TelemetryDataPose   *message);
size_t sonar_data__telemetry_data_pose__pack
                     (const SonarData__TelemetryDataPose   *message,
                      uint8_t             *out);
size_t sonar_data__telemetry_data_pose__pack_to_buffer
                     (const SonarData__TelemetryDataPose   *message,
                      ProtobufCBuffer     *buffer);
SonarData__TelemetryDataPose *
       sonar_data__telemetry_data_pose__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sonar_data__telemetry_data_pose__free_unpacked
                     (SonarData__TelemetryDataPose *message,
                      ProtobufCAllocator *allocator);
/* SonarData__TelemetryDataHeading methods */
void   sonar_data__telemetry_data_heading__init
                     (SonarData__TelemetryDataHeading         *message);
size_t sonar_data__telemetry_data_heading__get_packed_size
                     (const SonarData__TelemetryDataHeading   *message);
size_t sonar_data__telemetry_data_heading__pack
                     (const SonarData__TelemetryDataHeading   *message,
                      uint8_t             *out);
size_t sonar_data__telemetry_data_heading__pack_to_buffer
                     (const SonarData__TelemetryDataHeading   *message,
                      ProtobufCBuffer     *buffer);
SonarData__TelemetryDataHeading *
       sonar_data__telemetry_data_heading__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sonar_data__telemetry_data_heading__free_unpacked
                     (SonarData__TelemetryDataHeading *message,
                      ProtobufCAllocator *allocator);
/* SonarData__TelemetryDataDepth methods */
void   sonar_data__telemetry_data_depth__init
                     (SonarData__TelemetryDataDepth         *message);
size_t sonar_data__telemetry_data_depth__get_packed_size
                     (const SonarData__TelemetryDataDepth   *message);
size_t sonar_data__telemetry_data_depth__pack
                     (const SonarData__TelemetryDataDepth   *message,
                      uint8_t             *out);
size_t sonar_data__telemetry_data_depth__pack_to_buffer
                     (const SonarData__TelemetryDataDepth   *message,
                      ProtobufCBuffer     *buffer);
SonarData__TelemetryDataDepth *
       sonar_data__telemetry_data_depth__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sonar_data__telemetry_data_depth__free_unpacked
                     (SonarData__TelemetryDataDepth *message,
                      ProtobufCAllocator *allocator);
/* SonarData__TelemetryDataAltitude methods */
void   sonar_data__telemetry_data_altitude__init
                     (SonarData__TelemetryDataAltitude         *message);
size_t sonar_data__telemetry_data_altitude__get_packed_size
                     (const SonarData__TelemetryDataAltitude   *message);
size_t sonar_data__telemetry_data_altitude__pack
                     (const SonarData__TelemetryDataAltitude   *message,
                      uint8_t             *out);
size_t sonar_data__telemetry_data_altitude__pack_to_buffer
                     (const SonarData__TelemetryDataAltitude   *message,
                      ProtobufCBuffer     *buffer);
SonarData__TelemetryDataAltitude *
       sonar_data__telemetry_data_altitude__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sonar_data__telemetry_data_altitude__free_unpacked
                     (SonarData__TelemetryDataAltitude *message,
                      ProtobufCAllocator *allocator);
/* SonarData__TestDataRawPoses methods */
void   sonar_data__test_data__raw_poses__init
                     (SonarData__TestDataRawPoses         *message);
size_t sonar_data__test_data__raw_poses__get_packed_size
                     (const SonarData__TestDataRawPoses   *message);
size_t sonar_data__test_data__raw_poses__pack
                     (const SonarData__TestDataRawPoses   *message,
                      uint8_t             *out);
size_t sonar_data__test_data__raw_poses__pack_to_buffer
                     (const SonarData__TestDataRawPoses   *message,
                      ProtobufCBuffer     *buffer);
SonarData__TestDataRawPoses *
       sonar_data__test_data__raw_poses__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sonar_data__test_data__raw_poses__free_unpacked
                     (SonarData__TestDataRawPoses *message,
                      ProtobufCAllocator *allocator);
/* SonarData__RawRollAndpitch methods */
void   sonar_data__raw_roll_andpitch__init
                     (SonarData__RawRollAndpitch         *message);
size_t sonar_data__raw_roll_andpitch__get_packed_size
                     (const SonarData__RawRollAndpitch   *message);
size_t sonar_data__raw_roll_andpitch__pack
                     (const SonarData__RawRollAndpitch   *message,
                      uint8_t             *out);
size_t sonar_data__raw_roll_andpitch__pack_to_buffer
                     (const SonarData__RawRollAndpitch   *message,
                      ProtobufCBuffer     *buffer);
SonarData__RawRollAndpitch *
       sonar_data__raw_roll_andpitch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sonar_data__raw_roll_andpitch__free_unpacked
                     (SonarData__RawRollAndpitch *message,
                      ProtobufCAllocator *allocator);
/* SonarData__RawHeading methods */
void   sonar_data__raw_heading__init
                     (SonarData__RawHeading         *message);
size_t sonar_data__raw_heading__get_packed_size
                     (const SonarData__RawHeading   *message);
size_t sonar_data__raw_heading__pack
                     (const SonarData__RawHeading   *message,
                      uint8_t             *out);
size_t sonar_data__raw_heading__pack_to_buffer
                     (const SonarData__RawHeading   *message,
                      ProtobufCBuffer     *buffer);
SonarData__RawHeading *
       sonar_data__raw_heading__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sonar_data__raw_heading__free_unpacked
                     (SonarData__RawHeading *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SonarData__UngeorefAndTelemetry_Closure)
                 (const SonarData__UngeorefAndTelemetry *message,
                  void *closure_data);
typedef void (*SonarData__SonarData_Closure)
                 (const SonarData__SonarData *message,
                  void *closure_data);
typedef void (*SonarData__TelemetryDataPosition_Closure)
                 (const SonarData__TelemetryDataPosition *message,
                  void *closure_data);
typedef void (*SonarData__TelemetryDataPose_Closure)
                 (const SonarData__TelemetryDataPose *message,
                  void *closure_data);
typedef void (*SonarData__TelemetryDataHeading_Closure)
                 (const SonarData__TelemetryDataHeading *message,
                  void *closure_data);
typedef void (*SonarData__TelemetryDataDepth_Closure)
                 (const SonarData__TelemetryDataDepth *message,
                  void *closure_data);
typedef void (*SonarData__TelemetryDataAltitude_Closure)
                 (const SonarData__TelemetryDataAltitude *message,
                  void *closure_data);
typedef void (*SonarData__TestDataRawPoses_Closure)
                 (const SonarData__TestDataRawPoses *message,
                  void *closure_data);
typedef void (*SonarData__RawRollAndpitch_Closure)
                 (const SonarData__RawRollAndpitch *message,
                  void *closure_data);
typedef void (*SonarData__RawHeading_Closure)
                 (const SonarData__RawHeading *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor sonar_data__ungeoref__and__telemetry__descriptor;
extern const ProtobufCMessageDescriptor sonar_data__sonar_data__descriptor;
extern const ProtobufCMessageDescriptor sonar_data__telemetry_data_position__descriptor;
extern const ProtobufCMessageDescriptor sonar_data__telemetry_data_pose__descriptor;
extern const ProtobufCMessageDescriptor sonar_data__telemetry_data_heading__descriptor;
extern const ProtobufCMessageDescriptor sonar_data__telemetry_data_depth__descriptor;
extern const ProtobufCMessageDescriptor sonar_data__telemetry_data_altitude__descriptor;
extern const ProtobufCMessageDescriptor sonar_data__test_data__raw_poses__descriptor;
extern const ProtobufCMessageDescriptor sonar_data__raw_roll_andpitch__descriptor;
extern const ProtobufCMessageDescriptor sonar_data__raw_heading__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sonarData_2eproto__INCLUDED */
